name: syzygy
adopt-info: syzygy
summary: System Syzygy - A narrative meta-puzzle game
base: core18
description: |
  System Syzygy is a puzzle game, in the style of Cliff Johnson's 
  The Fool's Errand and 3 in Three, and of Andrew Plotkin's System's 
  Twilight..

grade: stable
confinement: strict

architectures:
  - build-on: [amd64,i386]

parts:
  syzygy:
    plugin: rust
    override-pull: |
      snapcraftctl pull
      sed -i 's|usr/lib/syzygy|/snap/syzygy/current|' src/gui/loader/path_linux.c
    source: https://github.com/mdsteele/syzygy.git
    override-build: |
      snapcraftctl build
      mkdir $SNAPCRAFT_PART_INSTALL/data
      cp -a data/fonts data/sprites data/backgrounds $SNAPCRAFT_PART_INSTALL/data
      cp -a target/release/syzygy $SNAPCRAFT_PART_INSTALL/bin
      snapcraftctl set-version $(git -C ../src describe --tags  | sed 's/v//')
    build-packages:
      - libsdl2-dev
    stage-packages:
      - libglu1-mesa
      - libsdl2-2.0-0
      - libpulse0

apps:
  syzygy:
    environment:
      SHELL: bash
      LC_ALL: C.UTF-8
      SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET}
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      SYZYGY_DATA_DIR: "$SNAP/data"
      HOME: "$SNAP_USER_DATA"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache" 
    command: syzygy
    plugs:
      - x11
      - pulseaudio
      - opengl
      - screen-inhibit-control
